{{- if .Values.registryAuthRequired }}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
  namespace: {{ .Values.rootNamespace }}
stringData:
  .dockerconfigjson: '{ "auths": { "ghcr.io": { "auth": "{{ .Values.githubRegAuthToken }}" } } }'
{{- end }}