apiVersion: v1
kind: Service
metadata:
  name: k8s-api
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: 16443
  selector:
    component: apiserver
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeapi-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: public
spec:
  rules:
  - host: k8s.t1m.me
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: k8s-api
            port:
              number: 16443
  tls:
  - hosts:
    - {{ .Values.baseAppUrl }}
  secretName: prod-ingress-tls-secret