apiVersion: v2
name: tins-stack-helm-chart
description: A simple helm chart for a django + nextjs setup
type: application
version: 0.1.0
appVersion: '1.16.0'
dependencies:
  - name: postgresql
    version: 12.4.2
    repository: https://charts.bitnami.com/bitnami