name: Build and push images

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'     
        required: true
        default: 'master'
      git_user:
        description: 'Your git user name'     
        required: true
        default: 'tbscode'
      unique_id:
        description: 'Unique id for the image tag'     
        required: true
        default: 'abc'

permissions:
  contents: read
  pages: write
  packages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  make_docs:
    runs-on: ubuntu-latest
    name: Build & Run tests
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.REPO_PAT }}
          submodules: recursive
      - name: Build and push backend prod image
        shell: 'script -q -e -c "bash {0}"'
        run: |
          make backend_build_prod
          make authorize_github_push gha_token=$GIT_PACKAGES_TOKEN
          make backend_push_prod_tag tag=$UNIQUE_ID gha_token=$GIT_PACKAGES_TOKEN
        env:
          MODE: 'remote'
          GIT_USER: ${{ github.event.inputs.git_user }}
          COMPOSE_DOCKER_CLI_BUILD: 1
          GIT_PACKAGES_TOKEN: ${{ secrets.GIT_PACKAGES_TOKEN }}
